using Test

include("test_configuration.jl")
include("test_paper_configuration.jl")
include("test_hamiltonian.jl")
include("test_paper_hamiltonian.jl")
include("test_initial_candidates.jl")
include("test_transverse_translation.jl")
include("test_vumps_runner.jl")
include("test_observables.jl")
include("test_branch_tracking.jl")
include("test_checkpoint.jl")
include("test_checkpoint_restart.jl")
include("test_cli.jl")
include("test_smoke.jl")
